database:
  dialect: postgres
  host: postgres-db
  port: 5432
  dbname: testdb
  loginId: testusr
  password: testusr
  migration: false

extension:
  master_generator: false
  cors_enabled: false
  security_enabled: true

log:
  request_log_format: ${remote_ip} ${account_loginid} ${uri} ${method} ${status}

security:
  auth_path:
    - /api/.*
  exclude_path:
    - /api/auth/login$
    - /api/account/
    - /api/auth/logout$
    - /api/health$
  user_path:
    - /api/.*
  admin_path:
    - /api/.*